// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/generalspec"
	"MSaaS-Framework/MSaaS/cmd/wizcraft/app/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GeneralSpecDelete is the builder for deleting a GeneralSpec entity.
type GeneralSpecDelete struct {
	config
	hooks    []Hook
	mutation *GeneralSpecMutation
}

// Where appends a list predicates to the GeneralSpecDelete builder.
func (gsd *GeneralSpecDelete) Where(ps ...predicate.GeneralSpec) *GeneralSpecDelete {
	gsd.mutation.Where(ps...)
	return gsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gsd *GeneralSpecDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gsd.sqlExec, gsd.mutation, gsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gsd *GeneralSpecDelete) ExecX(ctx context.Context) int {
	n, err := gsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gsd *GeneralSpecDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(generalspec.Table, sqlgraph.NewFieldSpec(generalspec.FieldID, field.TypeInt))
	if ps := gsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gsd.mutation.done = true
	return affected, err
}

// GeneralSpecDeleteOne is the builder for deleting a single GeneralSpec entity.
type GeneralSpecDeleteOne struct {
	gsd *GeneralSpecDelete
}

// Where appends a list predicates to the GeneralSpecDelete builder.
func (gsdo *GeneralSpecDeleteOne) Where(ps ...predicate.GeneralSpec) *GeneralSpecDeleteOne {
	gsdo.gsd.mutation.Where(ps...)
	return gsdo
}

// Exec executes the deletion query.
func (gsdo *GeneralSpecDeleteOne) Exec(ctx context.Context) error {
	n, err := gsdo.gsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{generalspec.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gsdo *GeneralSpecDeleteOne) ExecX(ctx context.Context) {
	if err := gsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
