services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - msaas_network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  wizcraft-dev:
    build:
      context: .
      dockerfile: ./cmd/wizcraft/Dockerfile.dev
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: ${POSTGRES_PORT}
      WIZCRAFT_PORT: ${WIZCRAFT_PORT}
    volumes:
      # 로컬 소스 디렉토리와 컨테이너의 /app 디렉토리를 바인딩
      - ./:/app
      - ${WIZCRAFT_VOLUME}:/msaas
    networks:
      - msaas_network
    ports:
      - "${WIZCRAFT_PORT}:${WIZCRAFT_PORT}"

networks:
  msaas_network:
    driver: bridge
